apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: ragserver
  name: ragserver
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      service: ragserver
  template:
    metadata:
      labels:
        service: ragserver
    spec:
      containers:
        - image: ${CONTAINER_REGISTRY}/ragserver:v0.0.1
          imagePullPolicy: Always
          name: ragserver
          ports:
            - containerPort: 9020
              hostPort: 9020
              protocol: TCP
          env:
            - name: RQLITE_URL
              value: http://admin:secret@rqlite.ragserver.svc.cluster.local:4001
            - name: OLLAMA_URL
              value: http://host.docker.internal:11434
      restartPolicy: Always
