apiVersion: v1
kind: Service
metadata:
  labels:
    service: ragserver
  name: ragserver
spec:
  type: LoadBalancer
  ports:
    - name: "9020"
      port: 9020
      targetPort: 9020
  selector:
    service: ragserver
