apiVersion: v1
kind: Service
metadata:
  labels:
    service: rqlite
  name: rqlite
spec:
  ports:
    - name: "4001"
      port: 4001
      targetPort: 4001
  selector:
    service: rqlite
  type: ClusterIP
